#!/bin/bash
parent_dir=$(dirname "$(pwd)")
for file in *.html; do
 if [ -e "$parent_dir/$file" ] && [ "$file" -nt "$parent_dir/$file" ]; then
        cp -u "$file" "$parent_dir"
        echo "Copied '$file' to the parent directory."
    elif [ ! -e "$parent_dir/$file" ]; then
        cp "$file" "$parent_dir"
        echo "Copied '$file' to the parent directory."
    fi
done
